spring.application.name=organization-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/organizationdb
spring.datasource.username=postgres
#here above is not name in which we are working , basically it is the default name or the username
spring.datasource.password=admin



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true