apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
  labels:
    app: organization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
        - name: organization-service
          image: organization-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: organization-service-config
            - secretRef:
                name: organization-service-secret
