apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APP_NAME: "{{ .Values.config.APP_NAME }}"
  CHATBOT_ENGINE_URL: "{{ .Values.config.CHATBOT_ENGINE_URL }}"
  SERVER_PORT: "{{ .Values.config.SERVER_PORT }}"
