apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  type: ClusterIP
  selector:
    app: organization-service
  ports:
    - port: {{ .Values.organizationService.port }}
      targetPort: {{ .Values.organizationService.port }}
