replicaCount: 2

image:
  repository: chatbot-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

config:
  APP_NAME: api-gateway
  CHATBOT_ENGINE_URL: http://chatbot-engine:8083
  SERVER_PORT: "8080"

secret:
  DB_PASSWORD: OTQ2MjgyMTczMg==
  API_TOKEN: OTQ2MjgyMTczMg==

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
chatbotEngine:
  image: chatbot-engine
  port: 8083
  replicas: 2

chatbotBridge:
  image: chatbot-bridge
  port: 8081
  replicas: 2

organizationService:
  image: organization-service
  port: 8082
  replicas: 2
