spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=chatbot-engine
spring.cloud.gateway.routes[0].uri=http://chatbot-engine:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/chat/**

