spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=chatbot-engine
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/chat/**